version: "3.1" 

services:
  mariadb:
    image: "mariadb:10.5" 
    restart: 'always'
    ports:
      - "3306:3306" 
    environment: 
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: login_node_jwt 
      MYSQL_USER: root 
      MYSQL_PASSWORD: root 
    networks:
      - app-network 

  adminer: 
    image: adminer 
    links:
      - mariadb 
    restart: always 
    ports:
      - '8080:8080'
    networks:
      - app-network 

networks: 
  app-network: 
    driver: bridge 